# Generated by Django 4.2.1 on 2024-02-17 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managerdashboard', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='club',
            field=models.CharField(default=models.CharField(max_length=100, null=True), max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='datereq',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='datewanted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='eventdetails',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='uname',
            field=models.CharField(default=models.CharField(max_length=100, null=True), max_length=100),
        ),
    ]
