# Generated by Django 4.2.1 on 2023-10-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='eventdetails',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
